export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  verifyOtp: "/verify-otp",
  forgotPassword: "/forgot-password",
  accountSetup: "/account-setup",
  authCallback: "/auth/callback",
  clerkSignIn: "/sign-in",
  clerkSignUp: "/sign-up",
  clerkComplete: "/auth/clerk/complete",
  overview: "/overview",
  clientes: "/clientes",
  adAccounts: "/ad-accounts",
  payments: "/payments",
  paymentsManual: "/payments/manual",
  cobros: "/cobros",
  gastos: "/gastos",
  affiliates: "/affiliates",
  creativeAnalyzer: "/creative-analyzer",
  pixels: "/pixels",
  profit: "/profit",
  support: "/support",
  adminLogin: "/admin/login",
  adminOverview: "/admin/overview",
  adminUnauthorized: "/admin/unauthorized",
  api: {
    auth: {
      logout: "/api/auth/logout",
      session: "/api/auth/session",
      adminAccess: "/api/auth/admin-access",
      otpRequest: "/api/auth/otp/request",
      otpProvision: "/api/auth/otp/provision",
    },
    onboarding: {
      status: "/api/onboarding/status",
    },
    wallet: "/api/wallet",
    payments: {
      intents: "/api/payments/intents",
      transactions: "/api/payments/transactions",
    },
    adAccounts: "/api/ad-accounts",
    support: {
      tickets: "/api/support/tickets",
    },
    notifications: "/api/notifications",
  },
} as const;
