/** Holistic Clerk appearance (sign-in / sign-up). */
export const holisticClerkAppearance = {
  layout: {
    logoPlacement: "none" as const,
    socialButtonsPlacement: "top" as const,
    socialButtonsVariant: "blockButton" as const,
    showOptionalFields: false,
  },
  variables: {
    colorPrimary: "#242522",
    colorBackground: "#ffffff",
    colorText: "#242522",
    colorTextSecondary: "#676961",
    colorInputBackground: "#ffffff",
    colorInputText: "#242522",
    colorNeutral: "#242522",
    colorDanger: "#b42318",
    colorSuccess: "#1f5c40",
    borderRadius: "12px",
    fontFamily: "var(--font-jakarta), ui-sans-serif, system-ui, sans-serif",
    fontFamilyButtons: "var(--font-jakarta), ui-sans-serif, system-ui, sans-serif",
    fontSize: "0.9375rem",
  },
  elements: {
    rootBox: { width: "100%" },
    cardBox: { width: "100%", boxShadow: "none", border: "none" },
    card: {
      boxShadow: "none",
      border: "none",
      borderRadius: "0",
      backgroundColor: "transparent",
      padding: "0",
    },
    headerTitle: {
      fontFamily: "var(--font-jakarta), sans-serif",
      fontWeight: "700",
      fontSize: "2rem",
      lineHeight: "1.15",
      letterSpacing: "-0.035em",
      color: "#242522",
    },
    headerSubtitle: {
      color: "#676961",
      fontSize: "0.9375rem",
      lineHeight: "1.6",
    },
    formFieldLabel: {
      color: "#242522",
      fontWeight: "600",
      fontSize: "0.8125rem",
    },
    formFieldInput: {
      borderRadius: "12px",
      minHeight: "52px",
      borderColor: "#d8dbd3",
      backgroundColor: "#ffffff",
      boxShadow: "none",
      fontSize: "0.95rem",
      "&:focus": {
        borderColor: "#b94708",
        boxShadow: "0 0 0 3px rgb(185 71 8 / 0.12)",
      },
    },
    formButtonPrimary: {
      backgroundColor: "#242522",
      color: "#ffffff",
      fontWeight: "700",
      borderRadius: "12px",
      minHeight: "52px",
      textTransform: "none",
      boxShadow: "none",
      fontSize: "0.95rem",
      "&:hover": {
        backgroundColor: "#3a3c36",
      },
      "&:disabled": { opacity: "0.55" },
      "&:focus-visible": { outline: "2px solid #b94708", outlineOffset: "3px" },
    },
    formButtonPrimaryIcon: {
      display: "none",
    },
    footer: {
      background: "transparent",
      boxShadow: "none",
      border: "none",
      padding: "24px 0 0",
    },
    footerActionLink: {
      color: "#b94708",
      fontWeight: "700",
    },
    formFieldAction: { color: "#b94708" },
    socialButtonsBlockButton: {
      borderRadius: "12px",
      minHeight: "52px",
      borderColor: "#d8dbd3",
      backgroundColor: "#ffffff",
      boxShadow: "none",
    },
    otpCodeFieldInput: {
      borderRadius: "12px",
      minHeight: "52px",
      borderColor: "#d8dbd3",
      boxShadow: "none",
    },
  },
};
